[[main]]
  name = "Docs"
  url = "/docs/notre-methode/parcours-client/"
  weight = 10

[[main]]
  name = "Résultats"
  url = "/resultats/"
  weight = 20

[[main]]
  name = "Votre avocat"
  weight = 30
  identifier = "Votreavocat"
  url = "/equipe/antonin-cholet/"

[[social]]
  name = "RDV visio"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-video\"><polygon points=\"23 7 16 12 23 17 23 7\"></polygon><rect x=\"1\" y=\"5\" width=\"15\" height=\"14\" rx=\"2\" ry=\"2\"></rect></svg>"
  url = "https://consultation.avocat.fr/consultation-video/forms.php?targetid=40539"
  post = "v0.1.0"
  weight = 20

[[social]]
  name = "RDV tel"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-phone-call\"><path d=\"M15.05 5A5 5 0 0 1 19 8.95M15.05 1A9 9 0 0 1 23 8.94m-1 7.98v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z\"></path></svg>"
  url = "https://consultation.avocat.fr/consultation-telephonique/forms.php?targetid=40539"
  weight = 10

[[footer]]
  name = "Mentions légales"
  url = "docs/legal/mentions-legales"
  weight = 10

[[footer]]
  name = "Données personnelles"
  url = "docs/legal/donnees-personnelles"
  weight = 10

[[docs]]
  name = "Notre expertise"
  weight = 10
  identifier = "notre-expertise"
  url = "/docs/notre-expertise/"

[[docs]]
  name = "Notre méthode"
  weight = 20
  identifier = "notre-methode"
  url = "/docs/notre-methode/"

[[docs]]
  name = "Nos tarifs"
  weight = 30
  identifier = "nos-tarifs"
  url = "/docs/nos-tarifs/"

[[docs]]
  name = "Légal"
  weight = 40
  identifier = "legal"
  url = "/docs/legal/"

[[docs]]
  name = "Contact"
  weight = 10
  identifier = "contact"
  url = "/docs/contact/"
